# Site
name: 'L4'
description: 'OpenSource Project'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/2019-1-OSS-L4'
disqus: 'skkuoss2019-1-l4'
email: '2680v4@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    woolim:
      name:           woolim
      name_kor:       조우림
      avatar:         /assets/images/woolim.png
      bio:            "오픈소스소프트웨어 L4 팀장입니다. L4 Github 페이지를 관리하고 있습니다."
      email:          2680v4@gmail.com
      github:         2680v4
<<<<<<< HEAD
    young:
      name:           young
      name_kor:       조영성
      avatar:         /assets/images/avatar_young.jpg
      bio:            "오픈소스소프트웨어 L4 팀원입니다."
      email:          choys0401@naver.com
      github:         choys0401	

 
=======
    seunghyeon:
      name:           seunghyeon
      name_kor:       김승현
      avatar:         /assets/images/seunghyeon.jpg
      bio:            "오픈소스소프트웨어 L4 member"
      email:          kim95175@gmail.com
      github:         kim95175
>>>>>>> 5b466b6b9f8a7931ee0c10f153a2c930abf7cb20
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: woolim
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
